### ISSUE TITLE
.xml demo content not uploading

### ISSUE THREAD

**Issue by dawnbuie** [webmandesign/demo-content#1]
Hi there - great site so far, i  got all the plugins installed correctly however when I trying importing https://github.com/webmandesign/demo-content/blob/master/auberge/content/demo-content-auberge.xml

nothing gets imported. 

I get errors like htis:
Failed to import author . Their posts will be attributed to the current user.
Failed to import “”: Invalid post type 
Menu Item “” already exists.
Failed to import ingredients Apple
Failed to import ingredients Black pepper
Failed to import ingredients Chicken

When I check the posted they don't have any content either. However I can see there is content in the original .xml file.  

thanks

**Comment by webmandesign** [comment]
Hi,

You need to activate plugin before you import demo content. Please read
https://github.com/webmandesign/demo-content/tree/master/auberge/content#before-you-install

Also, please understand that I provide support via
http://support.webmandesign.eu


Best regards,


*Oliver Juhas*

*WebMan Design*
www.webmandesign.eu
support.webmandesign.eu

Follow me on *Creative Market* <https://creativemarket.com/webmandesign>
Follow me on *Theme Forest*
<http://themeforest.net/user/webmandesign/follow>
WebMan Design at *WordPress.org*
<https://profiles.wordpress.org/webmandesign/>
Follow me on *Twitter* <http://twitter.com/#!/webmandesigneu>
Become a fan on *Facebook* <http://www.facebook.com/webmandesigneu>

**Comment by dawnbuie** [comment]
I did activate all plugins - that actually worked. The .xml doesn’t.

Dawn

**Comment by webmandesign** [comment]
Hi,

Please log a ticket at http://support.webmandesign.eu. I do not provide
support via email.

Best regards,


*Oliver Juhas*

*WebMan Design*
www.webmandesign.eu
support.webmandesign.eu

Follow me on *Creative Market* <https://creativemarket.com/webmandesign>
Follow me on *Theme Forest*
<http://themeforest.net/user/webmandesign/follow>
WebMan Design at *WordPress.org*
<https://profiles.wordpress.org/webmandesign/>
Follow me on *Twitter* <http://twitter.com/#!/webmandesigneu>
Become a fan on *Facebook* <http://www.facebook.com/webmandesigneu>
