### ISSUE TITLE
Just tried to load the demo on a virgin install; food menu is missing

### ISSUE THREAD

**Issue by tbee** [webmandesign/demo-content#2]
I untarred wordpress, let it create the database, installed the required plugins, imported the demo, nothing more:

[WARNING] Failed to import ingredients Apple
[WARNING] Failed to import ingredients Black pepper
[WARNING] Failed to import ingredients Chicken
[WARNING] Failed to import ingredients Curry powder
[WARNING] Failed to import nova_menu Desserts
[WARNING] Failed to import nova_menu Drinks
[WARNING] Failed to import nova_menu_item_label favorite
[WARNING] Failed to import nova_menu First courses
[WARNING] Failed to import ingredients Ginger
[WARNING] Failed to import nova_menu Main courses
[WARNING] Failed to import ingredients Mayonnaise
[WARNING] Failed to import ingredients Orange
[WARNING] Failed to import ingredients Raisins
[WARNING] Failed to import ingredients Salad
[WARNING] Failed to import ingredients Salt
[WARNING] Failed to import nova_menu_item_label spicy
[WARNING] Failed to import ingredients Yogurt
[WARNING] Failed to import nova_menu Alcohol
[WARNING] Failed to import nova_menu Cocktails
[WARNING] Failed to import nova_menu Coffee
[WARNING] Failed to import "Langoustine": Invalid post type nova_menu_item
[WARNING] Failed to import "Meal with recipe example": Invalid post type nova_menu_item
[WARNING] Failed to import "Heirloom Tomato": Invalid post type nova_menu_item
[WARNING] Failed to import "Artichoke Veloute": Invalid post type nova_menu_item
[WARNING] Failed to import "Dressed Crab Roll": Invalid post type nova_menu_item
[WARNING] Failed to import "Terrine of Goose Liver": Invalid post type nova_menu_item
[WARNING] Failed to import "Bresse Duck": Invalid post type nova_menu_item
[WARNING] Failed to import "Grouse": Invalid post type nova_menu_item
[WARNING] Failed to import "John Dory": Invalid post type nova_menu_item
[WARNING] Failed to import "Native Lobster": Invalid post type nova_menu_item
[WARNING] Failed to import "Turbot": Invalid post type nova_menu_item
[WARNING] Failed to import "Tournedos of Beef": Invalid post type nova_menu_item
[WARNING] Failed to import "Lion of Lamb": Invalid post type nova_menu_item
[WARNING] Failed to import "Roast Veal Fillet": Invalid post type nova_menu_item
[WARNING] Failed to import "Hazelnut Semi-Freddo": Invalid post type nova_menu_item
[WARNING] Failed to import "Champagne Cheesecake": Invalid post type nova_menu_item
[WARNING] Failed to import "Honey Parfait": Invalid post type nova_menu_item
[WARNING] Failed to import "Caramelised Pineapple": Invalid post type nova_menu_item
[WARNING] Failed to import "Exotic Soufflé": Invalid post type nova_menu_item
[WARNING] Failed to import "Mojito": Invalid post type nova_menu_item
[WARNING] Failed to import "Virgin Mojito": Invalid post type nova_menu_item
[WARNING] Failed to import "Dellicious": Invalid post type nova_menu_item
[WARNING] Failed to import "Whiskey": Invalid post type nova_menu_item
[WARNING] Failed to import "Vodka": Invalid post type nova_menu_item
[WARNING] Failed to import "Cappuccino": Invalid post type nova_menu_item
[WARNING] Failed to import "Arabica": Invalid post type nova_menu_item
[WARNING] Failed to import "Espresso": Invalid post type nova_menu_item
[WARNING] Failed to import "Iced coffee": Invalid post type nova_menu_item
This WordPress page does not have <strong>direct</strong> write file access. This plugin needs it in order to save the demo import xml file to the upload directory of your site. You can change this setting with these instructions: <a href="http://gregorcapuder.com/wordpress-how-to-set-direct-filesystem-method/" target="_blank">How to set <strong>direct</strong> filesystem method</a>.

**Comment by webmandesign** [comment]
Hi,

Please note that I provide support for my themes at https://support.webmandesign.eu/

I think you are referring to importing the Auberge theme demo content. https://webmandesign.github.io/docs/auberge/#demo-content

As stated in ["Required plugins" section](https://github.com/webmandesign/demo-content/tree/master/auberge#required-plugins), Jetpack plugin is required for food menu functionality (https://webmandesign.github.io/docs/auberge/#food-menu).

You can activate the Jetpack plugin and try to import the demo again or you can use a [reset plugin](https://wordpress.org/plugins/search/reset/) and do the import anew.

Best regards,

Oliver

**Comment by tbee** [comment]
Hi Oliver,

This seemed like the correct place to provide feedback, because this is where I got the demo files from. Do you want me to move the issue over?

The Jetpack plugin was installed and active. As are the other three. I made a totally clean install of both WP and the database, installed and activated Auberge, installed and actived the additional plugins, and ran the import.

I just now made the direct write file access change (last error) and ran the import again. This time there were no errors, but the food menu is still missing. How can I see if the food menu is setup? Documentation is unclear there (https://webmandesign.github.io/docs/auberge/#food-menu).

Regards, Tom

**Comment by tbee** [comment]
Ok. Figured it out: you need to active Jetpack twice. Once after the four plugins are installed, they all need to be activated. And then Jetpack needs to be activated in again, on a config page, to create a connection with wordpress.com. Two activations, each with a difference scope.

**Comment by webmandesign** [comment]
Hi Tom,

Indeed, Jetpack plugin requires additional activation via WordPress.com user account. Unfortunately, there is nothing I can do about this as this is a plugin feature. I suggest checking out Jetpack's website in theme docs (https://webmandesign.github.io/docs/auberge/#jetpack) but I should mention this additional activation process as well. Thanks for spotting this!

Best regards,

Oliver
